### ISSUE TITLE
Moving backgrounds

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-patch-compiler#24]
@P-Chang In Onikakushi we found some images that were apparently cut in half when the patch was made. The originals have irregular aspect ratio (see below). Apparently they were moving backgrounds on PS3 but GuraMan simply cut them in half since he didn't know how to do that in the engine. Maybe you could figure that out? You already experimented with some moving things before.

![004b](https://user-images.githubusercontent.com/539462/35172792-5c8ecf22-fd69-11e7-8f35-d72e14617162.png)
![031](https://user-images.githubusercontent.com/539462/35172793-5cab47ec-fd69-11e7-8b16-67bf954132e3.png)

**Comment by P-Chang** [comment]
OK, I'll look over it.

**Comment by enumag** [comment]
Ok. In that case we'll make pre-release without this.

**Comment by InochiPM** [comment]
If we need all of the panning pictures i have them.

**Comment by P-Chang** [comment]
https://github.com/P-Chang/onikakushi/commit/3311a771b92485db73d198d31183e0cc5dd061c8

I did some in my fork.
Some problem are reaming.

layer system was bit broken with large alpha channel 8 layer animation.
I added draw alpha channel only image 7 times and empty draw 7 times for initialize and revert layer size.

And if player exit to title menu during game is using big background, menu sprites will be bit broken.

Although, some of big background animation is probably bit broken or boring on 4:3 system.
And animation and initilize might be bit slow in lowend system( I can't be care lowend system since I changed CPU )

I can branch it with GEffectExtend flag, but scripts become bit complicated one than GCensor branch.

How we treat it?

**Comment by enumag** [comment]
> layer system was bit broken with large alpha channel 8 layer animation.
> I added draw alpha channel only image 7 times and empty draw 7 times for initialize and revert layer size.

I don't think I understand what the problem is here. Is 7 times not enough?

> And if player exit to title menu during game is using big background, menu sprites will be bit broken.
> It could avoid with add UI disable and disable right click menu when UI disable is true in DLL.

In my opinion this is an edge case mose people will never see anyway so I wouldn't worry about it too much. Can you post a screenshot of the broken menu for us?

> Although, some of big background animation is probably bit broken or boring on 4:3 system.

As far as I know 4:3 displays are less and less common (they are pretty much gone in my country). And I don't think we had any reports about the game being broken on 4:3 display. (The problem with menu would be even worse on 4:3 than it is on 16:10.) So probably not worth consideration.

> And animation and initilize might be bit slow in lowend system

It's difficult to say what it would cause on slow PC. I think we shouldn't worry about it for now - if we get performance-related reports about it then we can add the flag.

----

Your thoughts @ItaloKnox?

**Comment by P-Chang** [comment]
![broke](https://user-images.githubusercontent.com/29869319/35300335-70c18894-00cb-11e8-9259-0eb1a3e2d67f.png)
like this.

only happen in opening fade, game automatically resize until draw menu background.
Sure, it is really sensitivity issue.

8 and 7 is just miss post.

**Comment by ItaloKnox** [comment]
Hmm, I think it is fine? If we can disable the UI in problematic areas then I have nothing to complain about. At least for me, the pros are better than the cons.

**Comment by P-Chang** [comment]
Okay, I'll add some fix and push to master.
Master needs textures? I mean I know it should but release is soon and all of them are large.

**Comment by P-Chang** [comment]
Although, I found Japanese "LIES!" texture in archive.
But it looks bit small and font(one of mincho) have bigger shape, so I remade it.


ps3
![cs](https://user-images.githubusercontent.com/29869319/35351319-e1dbb6ae-0183-11e8-8ed2-fe7529475d63.png)



mine
![hg](https://user-images.githubusercontent.com/29869319/35351341-eff96056-0183-11e8-8487-466d8c5c5fd6.png)




Anyway I looked current mod "LIES" CG.

![02_c](https://user-images.githubusercontent.com/29869319/35351471-59b9c5c6-0184-11e8-9764-c285da36e89d.png)


it is bit far from Japanese one.
Basically Higurashi didn't much use horror font and Japanese one is similer in other text texture.

So, I tested with same as English text texture font("book antiqua", "bookman old style")

book antiqua
![antique](https://user-images.githubusercontent.com/29869319/35351351-f7b85cf2-0183-11e8-8ab6-e3569f9b6c38.png)


bookman old style
![bookman](https://user-images.githubusercontent.com/29869319/35351375-0b7c6e4a-0184-11e8-8da8-8dbb97317ef7.png)



Also, Mincho have image of military, top secret, melancholy in Anime culture(you will be confuse, me too) since Evangelion

So, I make it with VINCA STENCIL(military one)
![vinca](https://user-images.githubusercontent.com/29869319/35351383-12f452f0-0184-11e8-8b21-9357214faf53.png)



not looks bad, but it looks pretty much strong.



I'm not good in English fonts, any other ideas?

**Comment by enumag** [comment]
Honestly the PS3 default looks good to me.

I don"t know much about fonts, sorry.

**Comment by P-Chang** [comment]
After re-thinking, you are right. I destroy mine.

**Comment by P-Chang** [comment]
I'll use reseized "book antiqua" for now.
