### ISSUE TITLE
New text images

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-patch-compiler#27]
The games have quite a lot text images now - tips unlocking, bernkastell poems, new hanyuu poems, epilogue stuff... And since the sources are all different it's quite inconsistent. We don't have one place with all of these either since the poems are just being added now.

After the new graphics patches are done I'll send all the text files to @Inochi-PM to remake them. Until then we should decide about the fonts and style we want to use.

**Comment by InochiPM** [comment]
So, i have been looking at quite a few fonts for this since the font used for the main text files besides the unique ones, are a combination of two fonts by the same company one thats specifically for the kanji, and the other for the romaji so we cant combine two separate fonts like they did.

![tuki_waratte4 copy](https://user-images.githubusercontent.com/13459080/35476351-923ecfaa-037c-11e8-9e7f-6f6b1198cfc3.png)
For this font i remade the font they used from the existing font.  so that one is allready covered. 

However, the fonts for the other text are a bit more dificult. 
![hazi_fre_test](https://user-images.githubusercontent.com/13459080/35476364-b255ee0e-037c-11e8-8031-8c5b93a447e2.png)
 For the most part i used Cochin Regular, since it had the same amount of elegence that the original font had, but i was playing with the idea of using a handwriting for the poems themselves. here are the two examples. 

Using Cochin.
![si_onikakusi_j copy](https://user-images.githubusercontent.com/13459080/35476387-fb8355c6-037c-11e8-8c1e-4692c6dbcc3a.png)

Using Monotype Corsive
![si_onikakusi_j copy1](https://user-images.githubusercontent.com/13459080/35476406-521972bc-037d-11e8-8d55-4d25970d0e60.png)

Using AoyagiKouzanfontT
![oni_fre_1](https://user-images.githubusercontent.com/13459080/35476412-6493da7c-037d-11e8-86d8-4aa3ea9e5f96.png)

Any others would be greatly apriciated. 
Oh also, the Usoda text is actually a text overlay by itself. So that makes it much easier for me to edit it. we just have to decide on what font to use for it since its also the same font as before from all of the other text files. 
![oni_usoda](https://user-images.githubusercontent.com/13459080/35476436-bb434cae-037d-11e8-8a50-3995a24dc460.png)

**Comment by P-Chang** [comment]
I think original layouts are better than ps3 without English big font.

Handwriting fonts looks better than original one but we should keep original style I think.
Because, 07th use specific font in some location, but they didn't use in poem.

They changed poem in early days. but they didn't touch fonts.
I prefer release it as add-on. some of player will like well made fonts.

In this case, font that you found might not be correct one. I think it is Matisse Pro.

Although, Almost of Red big one can't be use as it as, 
these were made for working with ps2 and ps3 engine based. I planned another way.

**Comment by InochiPM** [comment]
@P-Chang i mean yeah the original layouts were good but with the sui poems their much more centered and didnt take up so much space in the middle. They also removed the smaller poem under berns name. As for the oroginal font im gonna past my findings from the Morisawa website since they use specifically their fonts like 85% of the time, 

Higurashi Sui Grungy Red Text - Tb Ko Shirushi-tai/TB古印体

Higurashi Sui Poems-TextCG - リュウミン M-KO/AR Dabiaosong
(These two fonts are used together, the first one is only romaji+katakana and AR is kanji only. So we could substitute a nice handwritten font for this altogether. )

**Comment by Grelo** [comment]
Once again i must agree with @P-Chang here.
I thought the initial idea was creating the best version possible while preserving the original work and it's feel.
Not "let's change everything now because i like it this way" . But maybe i missed the point of divergence.

**Comment by InochiPM** [comment]
@Grelo thats what im trying to do, since the font they used was a combination font the change had to be made, but thays what we are here for to pick what font we think would best fit the text files.
Since the ones we use now are just the vanila poems but upscaled making the text look nasty and blownout.

 I was playing  with the idea of having the poems look more handwritten because they are and the only difference between the PS3 poems and vanila is the smal poem under her name.

**Comment by Grelo** [comment]
@InochiPM
I like the second font but like @P-Chang said be we should probably keep the original font. 
The first one is close i think so something like that. Btw i like the font size you used so keep it because what we have now is too big and filling whole screen(my fault) and the original was closer to yours. 
And Bernkastel's name and space between names is too big in yours and i would keep the poem under name.
