### ISSUE TITLE
Video opening improvements

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-patch-compiler#46]
Recently we had two issues with the openings:
- Some players complain that the video contains spoilers.
- Oni has a short prologue so the video plays when launching the game and then again after two minutes in the story.

We should be able to use a Yes / No dialogue and a global flag(s) to fix this. Here is how I'd like to implement it:

- have a GPlayOpening flag, default to false
- when launching the game, play the video if GPlayOpening is true
- after prologue ask the user if they want to play the video
  - this should be a single screen like "Do you want to play the opening movie? (Might contain minor spoilers.) Yes / No"
  - If yes is selected, set GPlayOpening to true and play the video

The downside of this solution is that players upgrading from previous patch won't see the video. Maybe we could also play the video if they reached the end of the story but I'm not sure if they contain spoilers for other arcs too or not.

On Discord @irlPM suggested a bit more complicated solution:

- show the dialogue when the game is launched (but only once)
- even in this case it should still be just one simple screen
- set a global flag with the decision but don't play the video yet
- video should first play after prologue (if the answer was yes)
- after playing the video in story set another flag that would enable playing video on launch

The downside is that it is more complicated and needs more flags to be implemented. Also it feels a bit odd to ask about the opening but not play it immediately after asking but we still think it should first play during the story.

~~On the other hand it solves the problem with older players which is a good reason to go for this solution.~~ Actually it doesn't because I don't think we have a way to check if the player has already reached the end of the prologue. Or do we?

Which solution do you guys prefer? Do you have any other suggestions?

----

@idealpersona The prerequisite for this is solving the dialog function in Oni, Wata and Tata DLLs. We didn't need it until now so it's most likely not fixed yet. Do you think you could backport the fix from Hima?

**Comment by jwgrlrrajn** [comment]
I like the second idea, personally.

**Comment by Grelo** [comment]
I prefer irlPM's solution.

**Comment by idealpersona** [comment]
I wasn't aware we were playing the movies in two spots.  I like Enumag's solution as the second one seems just unnecessarily complicated.  UNLESS it is meant to be a more general control where the screen says "hey some modded content such as opening movies may contain spoilers.  Do you wish to include this content?" And have the flag that results from that choice control more things than just movies.  Then it would make more sense in front.  Currently, I can't think of anything that would encompass, but I don't discount the possibility.

Regarding the DLL issue I'm not sure what the problem or the fix is but I imagine if it's fixed in Hima we can find it and fix it in the other arcs.

**Comment by drojf** [comment]
can you have persistent variables in the higurashi engine? For umineko i'm planning to do the following with just one variable:

0 = flag not set
1 = play original video
2 = play PS3 video

**Comment by irlPM** [comment]
The other possibility would be taking off the video when you launch the game. Just letting in the storyline but personally putting a warning right before it plays kill totally the  game's atmosphere

**Comment by idealpersona** [comment]
@drojf Yes we have global flags.  The way I set it up in my proof of concept was this:

GSpoilerGuard - 1 if the player has asked to be protected against spoilers, 0 otherwise
GSpoilerCheck - 1 if has the player been prompted and chosen a value for GSpoilerGuard above.

I did it with 2 global flags because they lend more naturally to booleans, but they could easily become 1 value with 3 different states (Must ask, enabled, disabled)

**Comment by DoctorDiablo** [comment]
I thought of a third option that might be worth considering.  Instead of prompting the user in-game about the videos, we could make it a separate option in the installer.  That way, if the user doesn't want the videos we can avoid downloading them at all.

If the playvideo function is pointing to a nonexistent file, is the dll is smart enough to just ignore it and move on?  If not, we might have to do some tweaking to make that work.

**Comment by enumag** [comment]
@DoctorDiablo Interesting idea. Yes, the DLL is smart enough to handle that already. But I'm not sure if the installer can somehow show a warning about possible spoilers in the video.

cc @VocalNight @drojf

**Comment by ItaloKnox** [comment]
No, please leave the installer alone. Creating user logic implies we need to update the installer and the scripts, most likely leading me to make another post-installation script.

**Comment by enumag** [comment]
Alright, in that case we'll go with irl's suggestion since that seems to be preferred by most of the team.

I'll discuss the flags with idealpersona on Discord.

**Comment by enumag** [comment]
@irlPM I put together some code to implement the feature. Could you fill up the missing pieces, find the right places in the game and add it there? For now only in Tsumi I think. We should test this before puting it to all chapters. The flag will also be renamed later.

```
	// Game launch:

	if (GetGlobalFlag(GFlagForTest1) == 0) {
		// OutputLine() with the question

		char Item[2];

		if (GetGlobalFlag(GLanguage) == 1) {
			Item[0] = "Yes";
			Item[1] = "No";
		} else {
			Item[0] = "japanese yes";
			Item[1] = "japanese no";
		}

		Select( 2, Item );

		if (LoadValueFromLocalWork(SelectResult) == 0) {
			SetGlobalFlag(GFlagForTest1 , 1);
		}
		if (LoadValueFromLocalWork(SelectResult) == 1) {
			SetGlobalFlag(GFlagForTest1 , 2);
		}
	}

	if (GetGlobalFlag(GFlagForTest1) >= 3) {
		ModPlayMovie("movie");
	}


	// After prologue:

	if (GetGlobalFlag(GFlagForTest1) >= 2) {
		SetGlobalFlag(GFlagForTest1 , 3);
		ModPlayMovie("movie");
	}
```

**Comment by enumag** [comment]
@irlPM What is the current status here? Can I help somehow?

**Comment by enumag** [comment]
I finished the scripts in the `opening-question` branch of Onikakushi and Tsumihoroboshi. We'll need some DLL tweaking to finish this feature though.

Right now Tsumi shows the Yes/No selection like this:

![tsumi](https://user-images.githubusercontent.com/539462/44414356-d9dda500-a56d-11e8-8fad-05a1e51c8481.png)

Onikakushi is broken completely:

![oni](https://user-images.githubusercontent.com/539462/44414369-e3670d00-a56d-11e8-8e76-7744a5154b9f.png)

**Comment by enumag** [comment]
@idealpersona Can you look into it?

**Comment by enumag** [comment]
Also while you're fixing it, can you add a global flag like `GVideoOpening`? Right now we're using `GFlagForTest1` which is not ideal since it's a flag for testing purposes.

**Comment by idealpersona** [comment]
Alright, so there are two major issues with the Select operation in Oni through Tatari.  One of them is that SelectResult wasn't yet defined, and I've pulled that in to Oni and you in fact you wouldn't have seen that problem yet when you are at the point of @enumag 's screenshots.  But the visual bit seems more assets related if anyone wants to take a shot at it.  I was wondering why the options looked messed up, so i changed the "yes" option to all the uppercase letters ABCD...XYZ  and the "no" option to all the lowercase letters.

![image](https://user-images.githubusercontent.com/36429889/45260823-8ad9a180-b3ae-11e8-8bbf-52200e32609c.png)

Sure enough, that hints better at what's going on: for whatever reason, it seems to be using pieces of the UI as if they were members of a font sprite atlas, but it's not directly using textmeshpro for this, at least to my knowledge; it's using unity's built-in UILabels.  I was interested in porting everything over from Hima related to choices, but I think the code dependent on the assets which I don't have experience with.  Perhaps @enumag or @tellowkrinkle you guys would be better poised to look into this since you were on a closely-related issue?

**Comment by idealpersona** [comment]
To clarify: Oni through Tatari are using the unity built-in stuff (I say "using" loosely because it clearly doesn't work), while HImatsubushi uses TextMeshPro

**Comment by tellowkrinkle** [comment]
Think it could have anything to do with [this](https://github.com/07th-mod/higurashi-assembly/blob/10492b092cf251ff0b7c564cbf2c357a90b9b96a/TextRefresher.cs#L23)?  That class is what gets decoded from the assets in the asset bundle that contain text strings for things like menu options (which is why I was looking at it earlier) and it looks like they have both a TextMeshPro object and a UILabel that they use as a backup if the TextMeshPro object is null.

**Comment by enumag** [comment]
I looked at the diff between vanilla tatarigoroshi and vanilla himatsubushi. My guess is it all comes down to the changes made in the [ChoiceButton](https://github.com/07th-mod/higurashi-assembly/compare/tata-mg...hima-mg#diff-54cf7f26cf7c811345e06503f8d382c4) class. Is there something that prevents us from using Hima's ChoiceButton code in previous chapters? Or did you already try that and the screenshot above is the result?

**Comment by idealpersona** [comment]
@tellowkrinkle Well, [this](https://github.com/07th-mod/higurashi-assembly/blob/370f82bba4db74d9eb70ada57142a72513f0ebec/Assets.Scripts.UI.Choice/ChoiceButton.cs) class seems to be directly doing to a UILabel what your referenced code was doing on one branch, and it's reacting to my changes, so I don't think so, but I cannot be sure.  I used UABE for the first time to look at the ChoiceButton asset but it didn't tell me much - i was hoping I could see a component tree or something.

**Comment by enumag** [comment]
@idealpersona @tellowkrinkle Did you guys manage to figure out something?

**Comment by tellowkrinkle** [comment]
I've been busy with school work so I haven't had much time to mess around with it yet

**Comment by enumag** [comment]
Oh, that's fine of course, school takes priority. Thanks for telling me.

**Comment by enumag** [comment]
Implemented.
